name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ipmitool-exe
        path: ${{ github.workspace }}\install\bin\*.exe
