name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  windows:
    strategy:
      matrix:
        os: [ windows-2019 ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: install dependencies
      run: |-
        choco install cygwin -y
        choco install cyg-get -y
        # Line continuation in PowerShell is backtick. Weird as Windows.
        cyg-get gcc-g++ `
                make `
                automake `
                autoconf `
                m4 `
                libtool `
                libncurses-devel `
                libreadline-devel `
                libssl-devel `
                dos2unix `
                wget
        echo "C:/tools/cygwin/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:/tools/cygwin/usr/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - uses: actions/checkout@v2
    - name: convert line ends
      # checkout action on Windows apparently converts line ends
      # so we have to convert them back because cygwin bash can't
      # can't handle Windows line ends
      run: dos2unix bootstrap configure.ac csv-revision
    - name: bootstrap
      run: bash -c "./bootstrap"
    - name: configure
      run: bash -c "./configure"
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
      
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ matrix.os }}
        path: |
          **/*
